export const patternNameMapping: Record<string, string> = {
  "Quick Sort": "Quick Sort",
  "Merge Sort": "Merge Sort",
  "Stack Sort": "Stack Sort",
  "Heap Sort": "Heap Sort",
  "Bubble Sort": "Bubble Sort",
  "Selection Sort": "Selection Sort",
  "Insertion Sort": "Insertion Sort",
  "Binary Search": "Binary Search",
  "Binary Search on Answer": "Binary Search on Answer",
  "Linear Search": "Linear Search",
  "Two Sum": "Two Sum",
  "Two Sum Dict": "Two Sum Dict",
  "Two Sum Two Pointers": "Two Sum Two Pointers",
  "Dynamic Programming": "Dynamic Programming",
  "Dynamic Programming Pattern": "Dynamic Programming Pattern",
  "Dynamic Programming Fibonacci": "Dynamic Programming Fibonacci",
  "Dynamic Programming Iterative": "Dynamic Programming Iterative",
  "Dynamic Programming Coin Change": "Dynamic Programming Coin Change",
  "Greedy Activity Selection": "Greedy Activity Selection",
  "Greedy Fractional Knapsack": "Greedy Fractional Knapsack",
  "Greedy Job Scheduling": "Greedy Job Scheduling",
  "Greedy Huffman Coding": "Greedy Huffman Coding",
  "Greedy Dijkstra": "Greedy Dijkstra",
  "Sliding Window": "Sliding Window",
  "Bit Manipulation": "Bit Manipulation",
  "Topological Sort": "Topological Sort",
  "DFS Linked List": "DFS Linked List",
  "DFS Binary Tree": "DFS Binary Tree",
  "BFS Linked List": "BFS Linked List",
  "Stack Implementation": "Stack Implementation",
  "Queue Implementation": "Queue Implementation",
  "Linked List": "Linked List",
  "Circular Linked List": "Circular Linked List",
  "Hash Table": "Hash Table",
  "Monotonic Stack": "Monotonic Stack",
  "Monotonic Queue": "Monotonic Queue",
  "Two Pointers": "Two Pointers",
  "Prefix Sum": "Prefix Sum",
  "Floyd Cycle Detection": "Floyd Cycle Detection",
  "Matrix Traversal": "Matrix Traversal",
  "Matrix Traversal Recursive": "Matrix Traversal Recursive",
  "Matrix Spiral Traversal": "Matrix Spiral Traversal",
  "Matrix Spiral Recursive": "Matrix Spiral Recursive",
  "Binary Search Tree": "Binary Search Tree",
  "Trie Operations": "Trie Operations",
  "Ternary Search": "Ternary Search",
  "Jump Search": "Jump Search",
  "Exponential Search": "Exponential Search",
  "Heap Implementation": "Heap Implementation",
  "Divide and Conquer": "Divide and Conquer",
  "Articulation Points": "Articulation Points",
  "Graph Dijkstra": "Dijkstra's Algorithm",
  "Graph Kosaraju": "Kosaraju's Algorithm",
  "Network Flow": "Network Flow",
  "Strongly Connected Components": "Strongly Connected Components",
  "Maximum Bipartite Matching": "Maximum Bipartite Matching Algorithm",
  "A* Search": "A* Search",
  "Grid Traversal": "Grid Traversal",
  "State Compression DP": "State Compression DP",
  "Digit DP": "Digit DP",
  "Tree DP": "Tree DP",
  "Probability DP": "Probability DP",
  "Interpolation Search": "Interpolation Search",
  "Fibonacci Search": "Fibonacci Search",
  "Extended Euclidean": "Extended Euclidean",
  "Chinese Remainder Theorem": "Chinese Remainder Theorem",
  "Sieve of Eratosthenes": "Sieve of Eratosthenes",
  "Graph Articulation Points": "Graph Articulation Points",
  "Graph Bridges": "Graph Bridges",
  "Kadane's Algorithm": "Kadane's Algorithm",
  "Rabin-Karp": "Rabin-Karp",
  "KMP Algorithm": "KMP Algorithm",
  "Manacher's Algorithm": "Manacher's Algorithm",
  "Z Algorithm": "Z Algorithm",
  "Prim's Algorithm": "Prim's Algorithm",
  "Kruskal's Algorithm": "Kruskal's Algorithm",
  "Floyd-Warshall": "Floyd-Warshall",
  "Bellman-Ford": "Bellman-Ford",
  "A Star Search": "A Star Search",
  "Avl Tree": "Avl Tree",
  "B Tree": "B Tree",
  "Bellman Ford": "Bellman Ford",
  "Bfs Linked List": "Bfs Linked List",
  "Binary Search On Answer": "Binary Search On Answer",
  "Dfs Binary Tree": "Dfs Binary Tree",
  "Dfs Linked List": "Dfs Linked List",
  "Digit Dp": "Digit Dp",
  "Divide And Conquer": "Divide And Conquer",
  "Extended Euclidean Algorithm": "Extended Euclidean Algorithm",
  "Fenwick Tree": "Fenwick Tree",
  "Floyd Warshall": "Floyd Warshall",
  "Heavy Light Decomposition": "Heavy Light Decomposition",
  "Jump Search Algorithm": "Jump Search Algorithm",
  "Kadanes Algorithm": "Kadanes Algorithm",
  "Kmp Algorithm": "Kmp Algorithm",
  Knapsack: "Knapsack",
  "Kruskals Algorithm": "Kruskals Algorithm",
  Lca: "Lca",
  "Manachers Algorithm": "Manachers Algorithm",
  "Matrix Operations": "Matrix Operations",
  Memoization: "Memoization",
  "Prefix Sums": "Prefix Sums",
  "Prims Algorithm": "Prims Algorithm",
  "Probability Dp": "Probability Dp",
  Quickselect: "Quickselect",
  "Rabin Karp": "Rabin Karp",
  "Red Black Tree": "Red Black Tree",
  "Segment Tree": "Segment Tree",
  "Sieve Of Eratosthenes": "Sieve Of Eratosthenes",
  "State Compression Dp": "State Compression Dp",
  "Suffix Array": "Suffix Array",
  "Suffix Tree": "Suffix Tree",
  "Ternary Search Algorithm": "Ternary Search Algorithm",
  "Tree Dp": "Tree Dp",
  "Union Find": "Union Find",
  Graph: "Graph",
  Tree: "Tree",
  Backtracking: "Backtracking",
  Greedy: "Greedy",
  DFS: "DFS",
  BFS: "BFS",
  "Miller-Rabin": "Miller-Rabin",
  "Fast Fourier Transform": "Fast Fourier Transform",
};
