export const draculaTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "f8f8f2" },
    { token: "comment", foreground: "6272a4" },
    { token: "keyword", foreground: "ff79c6" },
    { token: "string", foreground: "f1fa8c" },
    { token: "number", foreground: "bd93f9" },
    { token: "operator", foreground: "ff79c6" },
    { token: "function", foreground: "50fa7b" },
    { token: "variable", foreground: "f8f8f2" },
    { token: "type", foreground: "8be9fd" },
    { token: "class", foreground: "8be9fd" },
    { token: "interface", foreground: "8be9fd" },
    { token: "enum", foreground: "8be9fd" },
    { token: "constant", foreground: "bd93f9" },
    { token: "parameter", foreground: "ffb86c" },
    { token: "property", foreground: "66d9ef" },
    { token: "punctuation", foreground: "f8f8f2" },
    { token: "delimiter", foreground: "f8f8f2" },
    { token: "bracket", foreground: "f8f8f2" },
    { token: "tag", foreground: "ff79c6" },
    { token: "attribute.name", foreground: "50fa7b" },
    { token: "attribute.value", foreground: "f1fa8c" },
  ],
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#44475a",
    "editor.selectionBackground": "#44475a",
    "editor.inactiveSelectionBackground": "#44475a80",
    "editorCursor.foreground": "#f8f8f2",
    "editorWhitespace.foreground": "#6272a480",
    "editorIndentGuide.background": "#6272a480",
    "editorIndentGuide.activeBackground": "#f8f8f280",
    "editor.selectionHighlightBackground": "#44475a80",
    "editor.wordHighlightBackground": "#44475a80",
    "editor.findMatchBackground": "#44475a80",
    "editor.findMatchHighlightBackground": "#44475a40",
    "editorBracketMatch.background": "#44475a80",
    "editorBracketMatch.border": "#f8f8f280",
    "editorOverviewRuler.border": "#282a36",
    "editorGutter.background": "#282a36",
    "editorError.foreground": "#ff5555",
    "editorWarning.foreground": "#ffb86c",
    "editorInfo.foreground": "#8be9fd",
    "editorHint.foreground": "#6272a4",
  },
};

export const solarizedTheme = {
  base: "vs" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "657b83" },
    { token: "comment", foreground: "93a1a1" },
    { token: "keyword", foreground: "b58900" },
    { token: "string", foreground: "2aa198" },
    { token: "number", foreground: "268bd2" },
    { token: "operator", foreground: "b58900" },
    { token: "function", foreground: "268bd2" },
    { token: "variable", foreground: "657b83" },
    { token: "type", foreground: "b58900" },
    { token: "class", foreground: "b58900" },
    { token: "interface", foreground: "b58900" },
    { token: "enum", foreground: "b58900" },
    { token: "constant", foreground: "268bd2" },
    { token: "parameter", foreground: "b58900" },
    { token: "property", foreground: "268bd2" },
    { token: "punctuation", foreground: "657b83" },
    { token: "delimiter", foreground: "657b83" },
    { token: "bracket", foreground: "657b83" },
    { token: "tag", foreground: "b58900" },
    { token: "attribute.name", foreground: "268bd2" },
    { token: "attribute.value", foreground: "2aa198" },
  ],
  colors: {
    "editor.background": "#fdf6e3",
    "editor.foreground": "#657b83",
    "editor.lineHighlightBackground": "#eee8d5",
    "editor.selectionBackground": "#eee8d5",
    "editor.inactiveSelectionBackground": "#eee8d580",
    "editorCursor.foreground": "#657b83",
    "editorWhitespace.foreground": "#93a1a180",
    "editorIndentGuide.background": "#93a1a180",
    "editorIndentGuide.activeBackground": "#657b8380",
    "editor.selectionHighlightBackground": "#eee8d580",
    "editor.wordHighlightBackground": "#eee8d580",
    "editor.findMatchBackground": "#eee8d580",
    "editor.findMatchHighlightBackground": "#eee8d540",
    "editorBracketMatch.background": "#eee8d580",
    "editorBracketMatch.border": "#657b8380",
    "editorOverviewRuler.border": "#fdf6e3",
    "editorGutter.background": "#fdf6e3",
    "editorError.foreground": "#dc322f",
    "editorWarning.foreground": "#b58900",
    "editorInfo.foreground": "#268bd2",
    "editorHint.foreground": "#93a1a1",
  },
};

export const lightTheme = {
  base: "vs" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "22223b" },
    { token: "comment", foreground: "6272a4" },
    { token: "keyword", foreground: "6366f1" },
    { token: "string", foreground: "10b981" },
    { token: "number", foreground: "f59e42" },
    { token: "operator", foreground: "6366f1" },
    { token: "function", foreground: "10b981" },
    { token: "variable", foreground: "22223b" },
    { token: "type", foreground: "6366f1" },
    { token: "class", foreground: "6366f1" },
    { token: "interface", foreground: "6366f1" },
    { token: "enum", foreground: "6366f1" },
    { token: "constant", foreground: "f59e42" },
    { token: "parameter", foreground: "6366f1" },
    { token: "property", foreground: "10b981" },
    { token: "punctuation", foreground: "22223b" },
    { token: "delimiter", foreground: "22223b" },
    { token: "bracket", foreground: "22223b" },
    { token: "tag", foreground: "6366f1" },
    { token: "attribute.name", foreground: "10b981" },
    { token: "attribute.value", foreground: "f59e42" },
  ],
  colors: {
    "editor.background": "#f8fafc",
    "editor.foreground": "#22223b",
    "editor.lineHighlightBackground": "#e2e8f0",
    "editor.selectionBackground": "#e2e8f0",
    "editor.inactiveSelectionBackground": "#e2e8f080",
    "editorCursor.foreground": "#22223b",
    "editorWhitespace.foreground": "#6272a480",
    "editorIndentGuide.background": "#6272a480",
    "editorIndentGuide.activeBackground": "#22223b80",
    "editor.selectionHighlightBackground": "#e2e8f080",
    "editor.wordHighlightBackground": "#e2e8f080",
    "editor.findMatchBackground": "#e2e8f080",
    "editor.findMatchHighlightBackground": "#e2e8f040",
    "editorBracketMatch.background": "#e2e8f080",
    "editorBracketMatch.border": "#22223b80",
    "editorOverviewRuler.border": "#f8fafc",
    "editorGutter.background": "#f8fafc",
    "editorError.foreground": "#ff5555",
    "editorWarning.foreground": "#f59e42",
    "editorInfo.foreground": "#6366f1",
    "editorHint.foreground": "#6272a4",
  },
};
