export const draculaTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "f8f8f2" },
    { token: "comment", foreground: "6272a4" },
    { token: "keyword", foreground: "ff79c6" },
    { token: "string", foreground: "f1fa8c" },
    { token: "number", foreground: "bd93f9" },
    { token: "operator", foreground: "ff79c6" },
    { token: "function", foreground: "50fa7b" },
    { token: "variable", foreground: "f8f8f2" },
    { token: "type", foreground: "8be9fd" },
    { token: "class", foreground: "8be9fd" },
    { token: "interface", foreground: "8be9fd" },
    { token: "enum", foreground: "8be9fd" },
    { token: "constant", foreground: "bd93f9" },
    { token: "parameter", foreground: "ffb86c" },
    { token: "property", foreground: "66d9ef" },
    { token: "punctuation", foreground: "f8f8f2" },
    { token: "delimiter", foreground: "f8f8f2" },
    { token: "bracket", foreground: "f8f8f2" },
    { token: "tag", foreground: "ff79c6" },
    { token: "attribute.name", foreground: "50fa7b" },
    { token: "attribute.value", foreground: "f1fa8c" },
  ],
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#44475a",
    "editor.selectionBackground": "#44475a",
    "editor.inactiveSelectionBackground": "#44475a80",
    "editorCursor.foreground": "#f8f8f2",
    "editorWhitespace.foreground": "#6272a480",
    "editorIndentGuide.background": "#6272a480",
    "editorIndentGuide.activeBackground": "#f8f8f280",
    "editor.selectionHighlightBackground": "#44475a80",
    "editor.wordHighlightBackground": "#44475a80",
    "editor.findMatchBackground": "#44475a80",
    "editor.findMatchHighlightBackground": "#44475a40",
    "editorBracketMatch.background": "#44475a80",
    "editorBracketMatch.border": "#f8f8f280",
    "editorOverviewRuler.border": "#282a36",
    "editorGutter.background": "#282a36",
    "editorError.foreground": "#ff5555",
    "editorWarning.foreground": "#ffb86c",
    "editorInfo.foreground": "#8be9fd",
    "editorHint.foreground": "#6272a4",
  },
};
