export const PATTERN_KEYS = [
  "Quick Sort",
  "Merge Sort",
  "Stack Sort",
  "Heap Sort",
  "Bubble Sort",
  "Selection Sort",
  "Insertion Sort",
  "Binary Search",
  "Binary Search on Answer",
  "Linear Search",
  "Two Sum",
  "Two Sum Dict",
  "Two Sum Two Pointers",
  "Dynamic Programming",
  "Dynamic Programming Pattern",
  "Dynamic Programming Fibonacci",
  "Dynamic Programming Iterative",
  "Dynamic Programming Coin Change",
  "Greedy Activity Selection",
  "Greedy Fractional Knapsack",
  "Greedy Job Scheduling",
  "Greedy Huffman Coding",
  "Greedy Dijkstra",
  "Sliding Window",
  "Bit Manipulation",
  "Topological Sort",
  "DFS Linked List",
  "DFS Binary Tree",
  "BFS Linked List",
  "Stack Implementation",
  "Queue Implementation",
  "Linked List",
  "Circular Linked List",
  "Hash Table",
  "Monotonic Stack",
  "Monotonic Queue",
  "Two Pointers",
  "Prefix Sum",
  "Floyd Cycle Detection",
  "Matrix Traversal",
  "Matrix Traversal Recursive",
  "Matrix Spiral Traversal",
  "Matrix Spiral Recursive",
  "Binary Search Tree",
  "Trie Operations",
  "Ternary Search",
  "Jump Search",
  "Exponential Search",
  "Heap Implementation",
  "Divide and Conquer",
  "Articulation Points",
  "Graph Dijkstra",
  "Graph Kosaraju",
  "Network Flow",
  "Strongly Connected Components",
  "Maximum Bipartite Matching",
  "A* Search",
  "Grid Traversal",
  "State Compression DP",
  "Digit DP",
  "Tree DP",
  "Probability DP",
  "Interpolation Search",
  "Fibonacci Search",
  "Extended Euclidean",
  "Chinese Remainder Theorem",
  "Sieve of Eratosthenes",
  "Graph Articulation Points",
  "Graph Bridges",
  "Kadane's Algorithm",
  "Rabin-Karp",
  "KMP Algorithm",
  "Manacher's Algorithm",
  "Z Algorithm",
  "Prim's Algorithm",
  "Kruskal's Algorithm",
  "Floyd-Warshall",
  "Bellman-Ford",
  "A Star Search",
  "Avl Tree",
  "B Tree",
  "Bellman Ford",
  "Bfs Linked List",
  "Binary Search On Answer",
  "Dfs Binary Tree",
  "Dfs Linked List",
  "Digit Dp",
  "Divide And Conquer",
  "Extended Euclidean Algorithm",
  "Fenwick Tree",
  "Floyd Warshall",
  "Heavy Light Decomposition",
  "Jump Search Algorithm",
  "Kadanes Algorithm",
  "Kmp Algorithm",
  "Knapsack",
  "Kruskals Algorithm",
  "Lca",
  "Manachers Algorithm",
  "Matrix Operations",
  "Memoization",
  "Prefix Sums",
  "Prims Algorithm",
  "Probability Dp",
  "Quickselect",
  "Rabin Karp",
  "Red Black Tree",
  "Segment Tree",
  "Sieve Of Eratosthenes",
  "State Compression Dp",
  "Suffix Array",
  "Suffix Tree",
  "Ternary Search Algorithm",
  "Tree Dp",
  "Union Find",
  "Graph",
  "Tree",
  "Backtracking",
  "Greedy",
  "DFS",
  "BFS",
  "Miller-Rabin",
  "Fast Fourier Transform",
] as const;

export type PatternKey = (typeof PATTERN_KEYS)[number];

export interface AlgorithmPattern {
  title: string;
  description: string;
  timeComplexity: string;
  spaceComplexity: string;
  pseudocode: string;
  example: string;
  implementation: string;
  category: string;
  pattern?: string;
}
