export const PATTERN_KEYS = [
  "Quick Sort",
  "Merge Sort",
  "Stack Sort",
  "Heap Sort",
  "Bubble Sort",
  "Selection Sort",
  "Insertion Sort",
  "Binary Search",
  "Binary Search on Answer",
  "Linear Search",
  "Two Sum",
  "Dynamic Programming",
  "Greedy",
  "Backtracking",
  "Sliding Window",
  "Bit Manipulation",
  "Topological Sort",
  "DFS",
  "BFS",
  "Stack Implementation",
  "Queue Implementation",
  "Linked List",
  "Circular Linked List",
  "Hash Table",
  "Graph",
  "Tree",
  "Binary Search Tree",
  "Heap Implementation",
  "Trie",
  "Monotonic Stack",
  "Monotonic Queue",
  "Two Pointers",
] as const;

export type PatternKey = (typeof PATTERN_KEYS)[number];
