import { algorithmPatterns } from "./patterns";
export const PATTERN_KEYS = Object.keys(algorithmPatterns);

export type PatternKey =
  | "Quick Sort"
  | "Merge Sort"
  | "Heap Sort"
  | "Bubble Sort"
  | "Selection Sort"
  | "Insertion Sort"
  | "Binary Search"
  | "Binary Search on Answer"
  | "Linear Search"
  | "Sliding Window"
  | "Two Pointers"
  | "Floyd Cycle Detection"
  | "Topological Sort"
  | "Null Pattern"
  | "Test Data"
  | "A* Search"
  | "Graph Dijkstra"
  | "Kadane's Algorithm"
  | "KMP Algorithm"
  | "Ternary Search"
  | "Exponential Search"
  | "Fibonacci Search"
  | "Interpolation Search"
  | "Jump Search"
  | "Manacher's Algorithm"
  | "Network Flow"
  | "Maximum Bipartite Matching"
  | "State Compression DP"
  | "Digit DP"
  | "Tree DP"
  | "Probability DP"
  | "Suffix Tree"
  | "Suffix Array"
  | "B Tree"
  | "AVL Tree"
  | "Red Black Tree"
  | "Fenwick Tree"
  | "Segment Tree"
  | "Activity Selection"
  | "Huffman Coding"
  | "Miller-Rabin Primality Test"
  | "Prime Factorization"
  | "Sieve of Eratosthenes"
  | "Chinese Remainder Theorem"
  | "Extended Euclidean"
  | "Grid Traversal"
  | "Matrix Chain Multiplication"
  | "Matrix Exponentiation"
  | "Floyd-Warshall"
  | "Kruskal"
  | "Prim"
  | "Graph Kosaraju"
  | "Bellman-Ford"
  | "BFS"
  | "DFS"
  | "Articulation Points"
  | "Union Find"
  | "Monotonic Queue"
  | "Monotonic Stack"
  | "Queue Implementation"
  | "Stack Implementation"
  | "Circular Linked List"
  | "Hash Table"
  | "Heap Implementation"
  | "Linked List"
  | "Fast Fourier Transform"
  | "Job Scheduling"
  | "Fractional Knapsack"
  | "Recursion"
  | "Divide and Conquer"
  | "Backtracking"
  | "Greedy"
  | "Greedy Job Scheduling"
  | "Greedy Fractional Knapsack"
  | "Graph"
  | "Matrix Spiral Traversal"
  | "Matrix Traversal"
  | "Prefix Sum"
  | "Rotate Matrix"
  | "Bit Manipulation"
  | "Stack Sort"
  | "Two Sum"
  | "Two Sum Two Pointers"
  | "Two Sum Dict"
  | "Trie Operations"
  | "Binary Search Tree"
  | "Graph Bridges"
  | "Graph SCC"
  | "Graph Kruskal"
  | "Tree"
  | "String"
  | "Matrix Spiral Recursive"
  | "Matrix Traversal Recursive"
  | "Dynamic Programming Fibonacci"
  | "Dynamic Programming Iterative"
  | "Dynamic Programming Coin Change"
  | "Dynamic Programming"
  | "Greedy Activity Selection"
  | "Greedy Huffman Coding"
  | "Greedy Dijkstra"
  | "Graph Bellman Ford"
  | "Graph Floyd Warshall"
  | "Graph Articulation Points"
  | "DFS Linked List"
  | "DFS Binary Tree"
  | "BFS Linked List"
  | "Strongly Connected Components"
  | "String Operations"
  | "Z Algorithm"
  | "Rabin Karp"
  | "Divide And Conquer"
  | "Extended Euclidean Algorithm"
  | "Sieve of Sundaram"
  | "Sieve of Atkin";

export interface AlgorithmPattern {
  title: string;
  description: string;
  timeComplexity: string;
  spaceComplexity: string;
  pseudocode: string;
  example: string;
  implementation: string;
  category: string;
  pattern?: string;
  keySteps?: string[];
}
