export type PatternKey =
  | "Bubble Sort"
  | "Quick Sort"
  | "Merge Sort"
  | "Insertion Sort"
  | "Selection Sort"
  | "Heap Sort"
  | "Counting Sort"
  | "Radix Sort"
  | "Bucket Sort"
  | "Shell Sort"
  | "Tim Sort"
  | "Binary Search"
  | "Linear Search"
  | "Jump Search"
  | "Interpolation Search"
  | "Exponential Search"
  | "Fibonacci Search"
  | "Breadth First Search"
  | "Depth First Search"
  | "Dijkstra"
  | "Bellman Ford"
  | "Floyd Warshall"
  | "Kruskal"
  | "Prim"
  | "Topological Sort"
  | "Kosaraju"
  | "Tarjan"
  | "Articulation Points"
  | "Bridges"
  | "Strongly Connected Components"
  | "Biconnected Components"
  | "Eulerian Path"
  | "Hamiltonian Path"
  | "Maximum Flow"
  | "Minimum Cut"
  | "Bipartite Matching"
  | "Stable Matching"
  | "Knapsack"
  | "Longest Common Subsequence"
  | "Longest Increasing Subsequence"
  | "Matrix Chain Multiplication"
  | "Coin Change"
  | "Edit Distance"
  | "Rod Cutting"
  | "Subset Sum"
  | "Partition Problem"
  | "Word Break"
  | "Palindrome Partitioning"
  | "Optimal Binary Search Tree"
  | "Activity Selection"
  | "Job Sequencing"
  | "Fractional Knapsack"
  | "Huffman Coding"
  | "Trie"
  | "Suffix Array"
  | "Suffix Tree"
  | "Fenwick Tree"
  | "Segment Tree"
  | "Binary Indexed Tree"
  | "Sparse Table"
  | "Disjoint Set Union"
  | "Union Find"
  | "Kruskal's Algorithm"
  | "Prim's Algorithm"
  | "Dijkstra's Algorithm"
  | "Bellman-Ford Algorithm"
  | "Floyd-Warshall Algorithm"
  | "Johnson's Algorithm"
  | "Ford-Fulkerson Algorithm"
  | "Edmonds-Karp Algorithm"
  | "Dinic's Algorithm"
  | "Push-Relabel Algorithm"
  | "Hopcroft-Karp Algorithm"
  | "Kuhn's Algorithm"
  | "Hungarian Algorithm"
  | "Gale-Shapley Algorithm"
  | "KMP Algorithm"
  | "Rabin-Karp Algorithm"
  | "Boyer-Moore Algorithm"
  | "Z Algorithm"
  | "Manacher's Algorithm"
  | "Suffix Automaton"
  | "Aho-Corasick Algorithm"
  | "Trie"
  | "Suffix Array"
  | "Suffix Tree"
  | "Fenwick Tree"
  | "Segment Tree"
  | "Binary Indexed Tree"
  | "Sparse Table"
  | "Disjoint Set Union"
  | "Union Find"
  | "Kruskal's Algorithm"
  | "Prim's Algorithm"
  | "Dijkstra's Algorithm"
  | "Bellman-Ford Algorithm"
  | "Floyd-Warshall Algorithm"
  | "Johnson's Algorithm"
  | "Ford-Fulkerson Algorithm"
  | "Edmonds-Karp Algorithm"
  | "Dinic's Algorithm"
  | "Push-Relabel Algorithm"
  | "Hopcroft-Karp Algorithm"
  | "Kuhn's Algorithm"
  | "Hungarian Algorithm"
  | "Gale-Shapley Algorithm"
  | "KMP Algorithm"
  | "Rabin-Karp Algorithm"
  | "Boyer-Moore Algorithm"
  | "Z Algorithm"
  | "Manacher's Algorithm"
  | "Suffix Automaton"
  | "Aho-Corasick Algorithm";
