import { PatternMapping } from "./types.js";

// This mapping ensures consistency between regular patterns and Monster Hunter patterns
export const patternMapping: PatternMapping = {
  // Sorting Patterns
  "Radix Sort": "Radix Sort",
  "Quick Sort": "Quick Sort",
  "Merge Sort": "Merge Sort",
  "Heap Sort": "Heap Sort",
  "Bubble Sort": "Bubble Sort",
  "Selection Sort": "Selection Sort",
  "Insertion Sort": "Insertion Sort",
  "Stack Sort": "Stack Sort",
  "Bucket Sort": "Bucket Sort",
  "Counting Sort": "Counting Sort",

  // Searching Patterns
  "Binary Search": "Binary Search",
  "Linear Search": "Linear Search",
  "Binary Search on Answer": "Binary Search on Answer",
  "Ternary Search": "Ternary Search",
  "Jump Search": "Jump Search",
  "Exponential Search": "Exponential Search",
  "Interpolation Search": "Interpolation Search",
  "Fibonacci Search": "Fibonacci Search",
  Quickselect: "Quickselect",

  // Dynamic Programming Patterns
  "Dynamic Programming": "Dynamic Programming",
  "Dynamic Programming Pattern": "Dynamic Programming Pattern",
  "Dynamic Programming Iterative": "Dynamic Programming Iterative",
  "Dynamic Programming Coin Change": "Dynamic Programming Coin Change",
  "State Compression DP": "State Compression DP",
  "Digit DP": "Digit DP",
  "Tree DP": "Tree DP",
  "Probability DP": "Probability DP",
  "Bitwise DP": "Bitwise DP",

  // Graph Patterns
  "A* Search": "A* Search",
  "Articulation Points": "Articulation Points",
  "Bellman-Ford": "Bellman-Ford",
  "Floyd-Warshall": "Floyd-Warshall",
  Kruskal: "Kruskal",
  "Strongly Connected Components": "Strongly Connected Components",
  "Maximum Bipartite Matching": "Maximum Bipartite Matching",
  "Topological Sort": "Topological Sort",
  Prim: "Prim",
  Kosaraju: "Kosaraju",
  Bridges: "Bridges",
  Dijkstra: "Dijkstra",
  "Network Flow": "Network Flow",
  "Heavy Light Decomposition": "Heavy Light Decomposition",
  "Hopcroft-Karp": "Hopcroft-Karp",
  "Ford-Fulkerson": "Ford-Fulkerson",
  "Kahn's Topological Sort": "Kahn's Topological Sort",
  "Graph Representation": "Graph Representation",
  "DFS Graph": "DFS Graph",
  "Spanning Tree": "Spanning Tree",

  // Data Structure Patterns
  "B Tree": "B Tree",
  "Circular Linked List": "Circular Linked List",
  "Fenwick Tree": "Fenwick Tree",
  "Linked List": "Linked List",
  "Segment Tree": "Segment Tree",
  "Union Find": "Union Find",
  "DFS Binary Tree": "DFS Binary Tree",
  "AVL Tree": "AVL Tree",
  "Binary Search Tree": "Binary Search Tree",
  "Red-Black Tree": "Red-Black Tree",
  "Binary Indexed Tree": "Binary Indexed Tree",
  "Doubly Linked List": "Doubly Linked List",
  "Hash Table": "Hash Table",
  "Heap Implementation": "Heap Implementation",
  "Queue Implementation": "Queue Implementation",
  "Stack Implementation": "Stack Implementation",
  "Lowest Common Ancestor": "Lowest Common Ancestor",
  Trie: "Trie",
  "Trie Operations": "Trie Operations",
  "Monotonic Queue": "Monotonic Queue",
  "Monotonic Stack": "Monotonic Stack",
  "Sparse Table": "Sparse Table",

  // String Patterns
  "String Operations": "String Operations",
  "Rabin-Karp": "Rabin-Karp",
  "Knuth-Morris-Pratt": "Knuth-Morris-Pratt",
  "Manacher's Algorithm": "Manacher's Algorithm",
  "Z Algorithm": "Z Algorithm",
  "Suffix Array": "Suffix Array",
  "Suffix Tree": "Suffix Tree",
  "String Hashing": "String Hashing",
  "Palindrome Partitioning": "Palindrome Partitioning",
  "Edit Distance": "Edit Distance",

  // Matrix Patterns
  "Matrix Operations": "Matrix Operations",
  "Matrix Traversal": "Matrix Traversal",
  "Matrix Traversal Recursive": "Matrix Traversal Recursive",
  "Matrix Spiral Traversal": "Matrix Spiral Traversal",
  "Matrix Spiral Recursive": "Matrix Spiral Recursive",
  "Matrix Chain Multiplication": "Matrix Chain Multiplication",
  "Matrix Exponentiation": "Matrix Exponentiation",
  "Grid Traversal": "Grid Traversal",

  // Number Theory Patterns
  "Chinese Remainder Theorem": "Chinese Remainder Theorem",
  "Extended Euclidean": "Extended Euclidean",
  "Fast Fourier Transform": "Fast Fourier Transform",
  "Sieve of Atkin": "Sieve of Atkin",
  "Sieve of Eratosthenes": "Sieve of Eratosthenes",
  "Sieve of Sundaram": "Sieve of Sundaram",
  "Miller-Rabin Primality Test": "Miller-Rabin Primality Test",
  "Karatsuba Multiplication": "Karatsuba Multiplication",
  "Shell Sort": "Shell Sort",

  // Other Patterns
  Backtracking: "Backtracking",
  "Bit Manipulation": "Bit Manipulation",
  "Divide and Conquer": "Divide and Conquer",
  "Floyd Cycle Detection": "Floyd Cycle Detection",
  "Kadane's Algorithm": "Kadane's Algorithm",
  "Prefix Sums": "Prefix Sums",
  Recursion: "Recursion",
  "Sliding Window": "Sliding Window",
  "Two Pointers": "Two Pointers",
  Memoization: "Memoization",
  "Fast and Slow Pointers": "Fast and Slow Pointers",
  Fibonacci: "Fibonacci",
  "Interval Scheduling": "Interval Scheduling",

  // Greedy Patterns
  "Activity Selection": "Activity Selection",
  "Fractional Knapsack": "Fractional Knapsack",
  "Huffman Coding": "Huffman Coding",
  "Job Scheduling": "Job Scheduling",
  "Hungarian Algorithm": "Hungarian Algorithm",
  Greedy: "Greedy",

  // BFS/DFS Patterns
  BFS: "BFS",
  "BFS Linked List": "BFS Linked List",
  DFS: "DFS",
  "DFS Linked List": "DFS Linked List",
  "LCA DFS": "LCA DFS",
  "Inorder Traversal": "Inorder Traversal",
  "Zigzag Traversal": "Zigzag Traversal",

  // Two Sum Variations
  "Two Sum": "Two Sum",
  "Two Sum Dict": "Two Sum Dict",
  "Two Sum Two Pointers": "Two Sum Two Pointers",
};
